version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      node.name: elasticsearch
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  #################################################################
  #                           DEV01                               #
  #################################################################
  logloader-dev01:
    build:
      context: log-loader/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      SAVEDTIMESTAMPSDIR: /var/lib/log-loader
      DOWNLOADBASEDIR: /var/log/salesforcecommercecloud
      # <INSTANCE> will be replaced by the instance name when running. You can also specify other, sans-instance, URLs to download from
      URLS: >
            https://<INSTANCE>-shop-rituals.demandware.net/on/demandware.servlet/webdav/Sites/Logs/;
      INSTANCE: dev01
      USERNAME: log-downloader
      PASSWORD: 9DA1^!hB
    networks:
      - elk
    volumes:
      - logs-dev01:/var/log/salesforcecommercecloud
      - log-loader-data:/var/lib/log-loader

  filebeat-dev01:
    build:
      context: filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      INSTANCE: dev01
    networks:
      - elk
    volumes:
      - logs-dev01:/usr/share/filebeat/logs

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  logs-dev01:
  elk-data:
  log-loader-data: