fields_under_root: true
fields:
  instance: ${INSTANCE}

filebeat.inputs:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.*
    - /usr/share/filebeat/logs/*/*.*

output.logstash:
    hosts: ['logstash:5044']